### ISSUE TITLE
Talk to Brisbane crew about dodu2014

### ISSUE THREAD

**Issue by auxesis** [devopsaustralia/general#2]

**Comment by auxesis** [comment]
@angusscown @mattcallanan: are you guys up for running Devopsdays in Brisbane next year? :tada:

We were thinking ~June + July.

**Comment by mattcallanan** [comment]
I'm keen to help

**Comment by auxesis** [comment]
@mattcallanan Awesome. 

The idea is to have a local team on the ground handling the local logistics (booking venue, catering, etc), and the parent @devopsaustralia organisation will provide support for budgeting, sponsorship, etc. 

Can you think of anyone else who would be keen in helping out organise?

**Comment by angusscown** [comment]
Pretty sure Bruce Morrison but will ask before putting his hand up for him.

**Comment by geekle** [comment]
@mattcallanan @angusscown That's great news.

**Comment by mattcallanan** [comment]
Spoke to Craig Smith today. He's keen to help. He's got a lot of Brisbane venue organising experience & can help promote the conference too.

**Comment by angusscown** [comment]
Ok, I also mentioned it to Bruce and he'd be ok to be involved too.

**Comment by auxesis** [comment]
:+1: Let's get this show on the road. :red_car: 

We should tee up a call in the next week or two to talk about next steps. 

@angusscown @mattcallanan you up for that?

**Comment by mattcallanan** [comment]
@auxesis yep, sounds good. Most nights from 7:30 are good for me. Have put some feelers out re: potential venues

**Comment by auxesis** [comment]
@mattcallanan awesome. How about next Tuesday (the 21st) at 19.30?

**Comment by geekle** [comment]
Count me in.

**Comment by mattcallanan** [comment]
Whoops. How about Wednesday? Thurs/Fri also good :)

-Matt

**Comment by auxesis** [comment]
LOL. 

Wednesday works for me.

**Comment by gergnz** [comment]
Awesome. I'll be there!

**Comment by auxesis** [comment]
Everything is being tracked in [devopsaustralia/2014](https://github.com/devopsaustralia/2014/issues).
