### ISSUE TITLE
Setup bank account for incorporated association

### ISSUE THREAD

**Issue by auxesis** [devopsaustralia/general#5]
Depends on #3.

**Comment by aussielunix** [comment]
@devopsaustralia/owners 
 What do we need from an account ?
- general transaction account
- multiple debit cards
- NFP discounts
- auto feed into [xero](http://www.xero.com)
- incoming bpay

**Comment by aussielunix** [comment]
[Ubank](https://www.ubank.com.au) is one of the new age online only banks that is backed by NAB.  
They combine a transaction account and a savings account together and you can have many savings targets.  
This eliminates the need for multiple accounts for things like: conference fund, meetup fund, etc etc

| Feature | Supported |
| :-- | :-: |
| general transaction account | ![yes](http://aussie.lunix.com.au/files/images/green_tick.png) |
| multiple debit cards | have emailed and asked |
| auto feed into xero | ![no](http://aussie.lunix.com.au/files/images/50px-RedX.png) |
| incoming bpay | ![yes](http://aussie.lunix.com.au/files/images/green_tick.png) |
| NFP discounts | ![yes](http://aussie.lunix.com.au/files/images/green_tick.png) appears to be fee free for [everyone.](https://ubankhelp.custhelp.com/app/answers/detail/a_id/8872) |

**Comment by auxesis** [comment]
Let's make a decision on this ASAP. 

Any objections to going with Ubank, or should we go with one of the big 4?

/cc @gergnz

**Comment by geekle** [comment]
Ubank looks good to me. :+1:

**Comment by gergnz** [comment]
fine by me.

**Comment by geekle** [comment]
Waiting on @aussielunix to check with Ubank if we're able to open an account without a linked account from another financial institution.

**Comment by aussielunix** [comment]
@geekle turns out ubank only do personal accounts at this stage.

**Comment by auxesis** [comment]
ABN is registered, @geekle says he's going to see if he can apply for the bank account online.

**Comment by geekle** [comment]
OK, @devopsaustralia/owners.
In accordance with the rules: `The Treasurer must ensure that at least one other committee member has access to the accounts and financial records of the Association.`
Access to the accounts will require attending a NAB branch for AUSTRAC verification.

Who would like access?

**Comment by gergnz** [comment]
@geekle well I guess that is me.  They should have my details. I have banked with them before.

**Comment by geekle** [comment]
@gergnz Great. I'll add you and I to start with and if any one else wants access, we can add them later.

**Comment by geekle** [comment]
Just an update. I started the process last week and I'm expecting a call in the next few days.
I'll have to get to a branch to show paperwork etc.

**Comment by geekle** [comment]
Didn't get the call. Chased them up today.

To be eligible for a regular account, we are required to provide:
- Certificate of Incorporation
- Account Authority Card (Signatures of the Signatories)
- General Meeting Minutes outlining positions or authorising a member to open an account

To be eligible for a fee-free community save account we additionally require:
- Income tax exemption certificate

**Comment by geekle** [comment]
Account opened on 27/05/2014.
