### ISSUE TITLE
Determine office holders for incorporated association

### ISSUE THREAD

**Issue by auxesis** [devopsaustralia/general#6]
Required to complete #3. 

We need to determine:
- President
- Vice-president
- Secretary
- Treasurer

**Comment by auxesis** [comment]
We should enumerate the legal requirements + responsibilities for each of the office holder positions.

**Comment by gergnz** [comment]
****\* DRAFT *****
@aussielunix wants to be ordinary committee member
@gergnz wants to be vice president
@auxesis wants to be secretary
@geekle +1 for president

@dlutzy would you like to be treasurer? (you don't have to be, it is just to kick off a discussion)

What are the legal requirements for each of these positions? @geekle

**Comment by auxesis** [comment]
@geekle can you find out if the secretary is ever required to physically visit a government facility in Victoria to perform their duties? This may have a bearing on who can most appropriately fill the secretary position.

**Comment by geekle** [comment]
@aussielunix @auxesis @gergnz @dlutzy I'll also require postal addresses for the application. Feel free to e-mail me them.

**Comment by geekle** [comment]
FYI - Some info regarding office holders: http://www.consumer.vic.gov.au/clubs-and-not-for-profits/incorporated-associations/running-an-incorporated-association/secretary-committee-and-office-holders

**Comment by dlutzy** [comment]
I still haven't done last year's tax.  I would not like to be treasurer.

**Comment by gergnz** [comment]
Neither have I :-(

**Comment by gergnz** [comment]
@gergnz will be treasurer
@aussielunix will be vice president
@dlutzy ordinary member
@auxesis secretary
@geekle president

**Comment by auxesis** [comment]
:tada: + :cocktail:

**Comment by aussielunix** [comment]
woo x :100:
