### ISSUE TITLE
Determine how GST works for incorporated associations

### ISSUE THREAD

**Issue by auxesis** [devopsaustralia/general#8]
@gergnz to determine:
- [ ] Do we need to register for GST?
- [ ] Do we need to register for GST to claim GST back?

**Comment by gergnz** [comment]
Email sent.

**Comment by gergnz** [comment]
Firstly, GST registration is only compulsory if your turnover is > $75,000pa.  Under that is optional.

Pros:
- Can claim back GST on expenses/inputs;
- Easier to deal with GST-registered businesses;

Cons:
- Need to complete regular BAS/paperwork;
- If you are dealing with general public who cannot claim GST input credits then price disadvantage;

**Comment by gergnz** [comment]
@auxesis @aussielunix @geekle Any other questions?  Thoughts?

How much do _people_ pay Vs their company?  If we are mostly dealing with companies, and then also paying for venues etc, it might be worth it.

Can anyone say how much work BAS is?

**Comment by auxesis** [comment]
> Can anyone say how much work BAS is?
> 
> Let's avoid having to do BAS at all costs.

We're running an organisation to facilitate the Australian DevOps
community, not navigate the intricacies and idiosyncrasies of Australian
tax law.

My accountant can handle submitting BAS on our behalf for a modest fee. I
assume yours offers the same sort of service @gergnz?

## 

w: http://fractio.nl/
t: @auxesis

**Comment by gergnz** [comment]
Agree @auxesis.  I have asked the cost question too, awaiting reply.  I don't care who we use.  I have no particularly strong ties with my accountant.  He just happens to be better and cheaper than my last, and does our business accounts.

**Comment by gergnz** [comment]
My accountant doesn't have insurance to cover not for profits so is unwilling to take us on. Over to @auxesis.

**Comment by auxesis** [comment]
Questions to answer are:
- [x] Can Lisa handle bookkeeping for us? How much?
- [x] Can Lisa register an ABN for us?
- [x] Do we need to register for GST status?
- [x] Do we need to register for GST to claim GST back?

**Comment by jamieslater** [comment]
would you like me to assist with this?

**Comment by auxesis** [comment]
Notes from my chat with Lisa just now: 
- As an incorporated association, we may not need an ABN, but we should get one to justify our existence to sponsors
- We should register an ABN, but not register for GST
- If revenue is less than $75k of revenue, we don't need to register for GST
- When we invoice sponsors, we don't need to mention GST
- Because we aren't GST registered, we don't even need to mention it to sponsors
- If we wanted to go above and beyond, we can mention "please note, because we're not registered for GST, so prices are GST-ex" at the bottom of invoices, but this is absolutely not mandatory. 
- As an incorporated association, we likely need to pay tax at the company tax rate, but Lisa will confirm within the next 2 days. 
- Lisa can handle the bookkeeping for us. 
- Lisa can register the ABN for us. 
- Costs: 
  - ABN registration == $80
  - Bookkeeping: Likely $600/year, ~$1,000/year worst case. All dependent on the complexity of our financials. She'll let us know if they get weird and it's going to cost towards $1,000/year
