### ISSUE TITLE
Register ABN

### ISSUE THREAD

**Issue by auxesis** [devopsaustralia/general#9]
Register an ABN for the DevOps Australia association. 

Need to determine whether we need to register for GST (per #8) before we can register for an ABN.

**Comment by auxesis** [comment]
As mentioned in #8, Lisa is registering the ABN for us. 

I'll update this issue when she confirms.

**Comment by auxesis** [comment]
- There are no requirements to lodge a tax return
- We don't need to pay tax for profits, provide we use the profits within the association
- We have to lodge one form a year with the Victorian government
- It costs about $60 to lodge
- There is one box to tick on that, "We require an independent review"
- Lisa can produce report of finances to satisfy this requirement
- Lisa will lodge the ABN application early next week, will email me the ABN once it's done.

**Comment by auxesis** [comment]
- [ ] @auxesis to introduce @gergnz to Lisa

**Comment by gergnz** [comment]
We need TFN or residential addresses please all to get the ABN now.  Send them my way please.
Let me know if you are not happy to provide.

/cc @aussielunix @dlutzy @geekle

**Comment by gergnz** [comment]
@auxesis to give the OK to use his address as the formal ABN business address.

**Comment by auxesis** [comment]
This is fine, and I've let Lisa know. 

I've supplied Lisa the residential addresses from our original application for an incorporated association. 

@devopsaustralia/owners please let me know if any of y'all have any objections.

**Comment by aussielunix** [comment]
@auxesis Was the address for me one in Goulburn or Windellama ?

**Comment by geekle** [comment]
@aussielunix Goulburn.
/cc @auxesis

**Comment by auxesis** [comment]
PO box in Goulburn, to be specific.

**Comment by aussielunix** [comment]
@auxesis @gergnz is that enough or do you need an actual residential address ?

**Comment by gergnz** [comment]
@aussielunix @auxesis I am guessing residential from what wording Lisa used: "or residential address required."

**Comment by auxesis** [comment]
@aussielunix I supplied your PO box, and asked Lisa to let me know if it wasn't sufficient.

**Comment by gergnz** [comment]
@aussielunix sorry the PO Box isn't enough.  Can you supply myself or @auxesis your TFN or residential address.

We also require date of births now too :-(

/cc @geekle @dlutzy

**Comment by auxesis** [comment]
I've forwarded @aussielunix + @dlutzy's details. 

Lisa now has all the information she needs to lodge the application, and is doing so this arvo.

**Comment by auxesis** [comment]
We are registered! :tada: :tada: :tada: :tada: :tada: :tada: 

```
ABN for DEVOPS AUSTRALIA INCORPORATED
Your ABN: 35167927157
ABN status: Active from 07/02/2014
```

Lisa says it was all a bit of a battle, and @aussielunix isn't currently associated with the ABN. She'll get it updated in the next few days.

**Comment by auxesis** [comment]
Just one note - we're [not showing up in the ABR's ABN lookup](http://abr.business.gov.au/SearchByName.aspx?SearchText=devops). 

Chalk it up to government being eventually consistent.

**Comment by auxesis** [comment]
@devopsaustralia/2014 we have the ABN registered now. 

@geekle is making a move on #5 (getting the bank account registered).
